title: Posts
description: 
author: Aditya
github: https://github.com/aditya-369
about: I am a computer science Undergrad student who is intrested in many things like programming, music, sports...and many things that makes me curious.
avatar_url: /static/img/ad.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/aditya.sai.311"
    - icon: fa-twitter
      link: "https://twitter.com/Aditya__369"
    - icon: fa-linkedin
      link: "https://in.linkedin.com/in/aditya-prayaga-22b83a139"
    - icon: fa-github
      link: "https://github.com/aditya-369"

share:
  twitter_username: Aditya__369
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/

url: "https://www.aditya-369.ml/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
